# Generated by Django 4.2.5 on 2023-09-12 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tasks', '0002_task_ownertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ownerTask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.user'),
        ),
    ]
